-- INSERTS CENTROS FORENSES (Autor_Examen tiene un valor deafult, por eso no lo pongo)
INSERT INTO CENTROS_FORENSES VALUES (1, 'Centro1', 'España', 10);
INSERT INTO CENTROS_FORENSES VALUES (2, 'Centro2', 'Francia', 4);
INSERT INTO CENTROS_FORENSES VALUES (3, 'Centro3', 'Portugal', 12);
INSERT INTO CENTROS_FORENSES VALUES (4, 'Centro4', 'Italia', 8);
INSERT INTO CENTROS_FORENSES VALUES (5, 'Centro5', 'Alemania', 6);

--INSERTS MUESTRAS FORENSES
INSERT INTO MUESTRAS_FORENSES VALUES (1, 1412, 'Saliva', '02/06/2026', 'Estado', 2);
INSERT INTO MUESTRAS_FORENSES VALUES (2, 1182, 'Pelo', '02/06/2026', 'Estado', 1);
INSERT INTO MUESTRAS_FORENSES VALUES (3, 6742, 'Muestra', '02/06/2026', 'Estado', 5);
INSERT INTO MUESTRAS_FORENSES VALUES (4, 1248, 'Pelo', '02/06/2026', 'Estado', 3);
INSERT INTO MUESTRAS_FORENSES VALUES (5, 8753, 'Saliva', '02/06/2026', 'Estado', 3);

--INSERTS INFORMES FORENSES

INSERT INTO INFORMES_FORENSES VALUES (1, 0, 10, 'Muy peligroso', 2);
INSERT INTO INFORMES_FORENSES VALUES (2, 1, 5, 'Peligroso', 3);
INSERT INTO INFORMES_FORENSES VALUES (3, 0, 8, 'No Concluido', 1);
INSERT INTO INFORMES_FORENSES VALUES (4, 1, 12, 'No peligroso', 4);
INSERT INTO INFORMES_FORENSES VALUES (5, 0, 1, 'No Concluido', 5);